const data = {
    products: [
      {
        _id: '1',
        name: 'Be',
        artist: 'Common',
        category: 'Hip Hop',
        image: '/images/01-common-be.jpeg',
        price: 30,
        label: 'Gefeen',
        rating: 4.5,
        numReviews: 10,
        description: 'New Unselled',
      },
      {
        _id: '2',
        name: 'Dangerous',
        artist: 'Michael Jackson',
        category: 'Pop',
        image: '/images/02-michaelj-dangerous.jpg',
        price: 25,
        label: 'Michael Label',
        rating: 5,
        numReviews: 20,
        description: 'New Unselled',
      },
      {
        _id: '3',
        name: 'Misseucation of Lauryn Hill',
        artist: 'Lauryn Hill',
        category: 'Hip Hop',
        image: '/images/03-miseducation-lauryn.jpeg',
        price: 20,
        label: 'Gefeen',
        rating: 4,
        numReviews: 6,
        description: 'New Unselled',
      },
      {
        _id: '4',
        name: 'Queen',
        artist: 'Queen',
        category: 'Rock',
        image: '/images/04-queen-queen.png',
        price: 31,
        label: 'Gefeen',
        rating: 5,
        numReviews: 13,
        description: 'New Unselled',
      },
      {
        _id: '5',
        name: 'The Bends',
        artist: 'Radiohead',
        category: 'Rock',
        image: '/images/05-radiohead-thebends.png',
        price: 35,
        label: 'Gefeen',
        rating: 5,
        numReviews: 15,
        description: 'New Unselled',
      },
      {
        _id: '6',
        name: 'Californication',
        artist: 'Red Hot Chilli Peppers',
        category: 'Rock',
        image: '/images/06-redhot-californication.jpg',
        price: 20,
        label: 'Gefeen',
        rating: 4,
        numReviews: 14,
        description: 'New Unselled',
      },
      {
        _id: '7',
        name: 'Tha Goodfather',
        artist: 'Snoop Dog',
        category: 'Hip Hop',
        image: '/images/07-snoopdog-thagoodfather.jpg',
        price: 22,
        label: 'Gefeen',
        rating: 4,
        numReviews: 14,
        description: 'New Unselled',
      },
      {
        _id: '8',
        name: 'Bjork',
        artist: 'Bjork',
        category: 'World Music',
        image: '/images/08-bjork-bjork.jpg',
        price: 32,
        label: 'Gefeen',
        rating: 5,
        numReviews: 7,
        description: 'New Unselled',
      },

    ],
  };
  export default data;